// <auto-generated />
using System;
using Caching.Demo.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Caching.Demo.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Caching.Demo.Repository.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed1dd774-14a8-45cd-99bb-5567dba9aad7"),
                            Name = "Product 1",
                            Price = 10.0m
                        },
                        new
                        {
                            Id = new Guid("a42e98cc-ae38-4fa9-abb9-350ccf654f93"),
                            Name = "Product 2",
                            Price = 20.0m
                        },
                        new
                        {
                            Id = new Guid("3db7e087-bec7-4605-8c73-89edd88eb693"),
                            Name = "Product 3",
                            Price = 30.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
